# Generated by Django 4.2.17 on 2025-02-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name_plural': 'districts'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name_plural': 'provinces'},
        ),
    ]
