volumes:
  core_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: core_local_django
    container_name: core_local_django
    depends_on:
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.tidb
    ports:
      - '8000:8000'
    command: /start

  redis:
    image: docker.io/redis:6
    container_name: core_local_redis

    volumes:
      - core_local_redis_data:/data

  celeryworker:
    <<: *django
    image: core_local_celeryworker
    container_name: core_local_celeryworker
    depends_on:
      - redis
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: core_local_celerybeat
    container_name: core_local_celerybeat
    depends_on:
      - redis
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: core_local_flower
    container_name: core_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
