# Generated by Django 4.2.23 on 2025-08-05 08:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the category', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Category name (must be unique)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description of the category', null=True)),
                ('slug', models.SlugField(blank=True, help_text='SEO-friendly URL slug (auto-generated from name)', max_length=120, unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title (recommended: 50-60 characters)', max_length=160)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description (recommended: 150-160 characters)', max_length=320)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active and visible')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this category should be featured prominently')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Sort order for displaying categories')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the category was last updated')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ecommerce.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['name'], name='ecommerce_c_name_f3a40e_idx'), models.Index(fields=['slug'], name='ecommerce_c_slug_53629f_idx'), models.Index(fields=['is_active'], name='ecommerce_c_is_acti_1e5a3b_idx'), models.Index(fields=['is_featured'], name='ecommerce_c_is_feat_e4018e_idx'), models.Index(fields=['sort_order'], name='ecommerce_c_sort_or_480898_idx'), models.Index(fields=['created_at'], name='ecommerce_c_created_17ce26_idx')],
            },
        ),
    ]
