# Generated by Django 4.2.23 on 2025-08-05 09:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the category', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Category name (must be unique)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description of the category', null=True)),
                ('slug', models.SlugField(blank=True, help_text='SEO-friendly URL slug (auto-generated from name)', max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active and visible')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this category should be featured prominently')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the category was last updated')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the subcategory', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Subcategory name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description of the subcategory', null=True)),
                ('slug', models.SlugField(blank=True, help_text='SEO-friendly URL slug (auto-generated from name)', max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subcategory is active and visible')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this subcategory should be featured prominently')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the subcategory was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the subcategory was last updated')),
                ('category', models.ForeignKey(help_text='Parent category for this subcategory', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ecommerce.productcategory')),
            ],
            options={
                'verbose_name': 'Product SubCategory',
                'verbose_name_plural': 'Product SubCategories',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['name'], name='ecommerce_p_name_75c86a_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['slug'], name='ecommerce_p_slug_a2f612_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['is_active'], name='ecommerce_p_is_acti_9feda9_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['is_featured'], name='ecommerce_p_is_feat_a95c32_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['created_at'], name='ecommerce_p_created_6e4454_idx'),
        ),
        migrations.AddIndex(
            model_name='productsubcategory',
            index=models.Index(fields=['name'], name='ecommerce_p_name_9e1b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='productsubcategory',
            index=models.Index(fields=['slug'], name='ecommerce_p_slug_1135fb_idx'),
        ),
        migrations.AddIndex(
            model_name='productsubcategory',
            index=models.Index(fields=['is_active'], name='ecommerce_p_is_acti_81a638_idx'),
        ),
        migrations.AddIndex(
            model_name='productsubcategory',
            index=models.Index(fields=['is_featured'], name='ecommerce_p_is_feat_058bba_idx'),
        ),
        migrations.AddIndex(
            model_name='productsubcategory',
            index=models.Index(fields=['category'], name='ecommerce_p_categor_472fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='productsubcategory',
            index=models.Index(fields=['created_at'], name='ecommerce_p_created_f7f47a_idx'),
        ),
        migrations.AddConstraint(
            model_name='productsubcategory',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_subcategory_per_category'),
        ),
    ]
