# Generated by Django 4.2.23 on 2025-08-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_productcategory_productsubcategory_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Categorys', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveConstraint(
            model_name='productsubcategory',
            name='unique_subcategory_per_category',
        ),
        migrations.RemoveIndex(
            model_name='productcategory',
            name='ecommerce_p_name_75c86a_idx',
        ),
        migrations.RemoveIndex(
            model_name='productcategory',
            name='ecommerce_p_slug_a2f612_idx',
        ),
        migrations.RemoveIndex(
            model_name='productcategory',
            name='ecommerce_p_is_acti_9feda9_idx',
        ),
        migrations.RemoveIndex(
            model_name='productcategory',
            name='ecommerce_p_is_feat_a95c32_idx',
        ),
        migrations.RemoveIndex(
            model_name='productcategory',
            name='ecommerce_p_created_6e4454_idx',
        ),
    ]
