# Generated by Django 4.2.23 on 2025-08-06 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productsubcategory',
            name='ecommerce_p_name_9e1b5d_idx',
        ),
        migrations.RemoveIndex(
            model_name='productsubcategory',
            name='ecommerce_p_slug_1135fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='productsubcategory',
            name='ecommerce_p_is_acti_81a638_idx',
        ),
        migrations.RemoveIndex(
            model_name='productsubcategory',
            name='ecommerce_p_is_feat_058bba_idx',
        ),
        migrations.RemoveIndex(
            model_name='productsubcategory',
            name='ecommerce_p_categor_472fc1_idx',
        ),
        migrations.RemoveIndex(
            model_name='productsubcategory',
            name='ecommerce_p_created_f7f47a_idx',
        ),
    ]
