# Generated by Django 4.2.23 on 2025-08-11 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0004_remove_productsubcategory_ecommerce_p_name_9e1b5d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the product', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='SEO-friendly URL slug (auto-generated from name)', max_length=220, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the product')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=29)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Available stock quantity')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', help_text='Product status', max_length=10)),
                ('is_approve', models.BooleanField(default=False, help_text='Whether this product is approved by admin (only changeable in admin)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the product was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the product was last updated')),
                ('category', models.ForeignKey(help_text='Category for this product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecommerce.productcategory')),
                ('user', models.ForeignKey(help_text='User who owns this product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the product image', primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Product image file', upload_to='product_images/')),
                ('caption', models.CharField(blank=True, default='', help_text='Optional caption for the image', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary image for the product')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Sort order for displaying images')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the image was uploaded')),
                ('product', models.ForeignKey(help_text='Product this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecommerce.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
