# Generated by Django 4.2.23 on 2025-08-12 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0004_remove_productsubcategory_ecommerce_p_name_9e1b5d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the product', primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, help_text='Main product image', null=True, upload_to='ecommerce/products/images/')),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('slug', models.SlugField(help_text='SEO-friendly URL slug (auto-generated from name)', max_length=220, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the product')),
                ('available_stock', models.PositiveIntegerField(default=0, help_text='Available stock quantity')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', help_text='Product status', max_length=10)),
                ('approval_status', models.CharField(choices=[('pending', 'Waiting for approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status of the product by admin', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the product was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the product was last updated')),
                ('category', models.ForeignKey(help_text='Category for this product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecommerce.productcategory')),
                ('user', models.ForeignKey(help_text='User who owns this product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Product image file', upload_to='ecommerce/products/images/')),
                ('caption', models.CharField(blank=True, default='', help_text='Optional caption for the image', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the image was uploaded')),
                ('product', models.ForeignKey(help_text='Product this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecommerce.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['created_at'],
            },
        ),
    ]
