# Generated by Django 4.2.23 on 2025-08-18 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0005_product_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the cart item', primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of this product in the cart')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the item was added to cart')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the cart item was last updated')),
                ('product', models.ForeignKey(help_text='Product in this cart item', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='ecommerce.product')),
                ('user', models.ForeignKey(help_text='User who owns this cart item', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'ordering': ['created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
