# Generated by Django 4.2.23 on 2025-08-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_product_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['created_at'], 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='available_stock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_approve',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='product',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Waiting for approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status of the product by admin', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Main product image', null=True, upload_to='ecommerce/products/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='SEO-friendly URL slug (auto-generated from name)', max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Product image file', upload_to='ecommerce/products/images/'),
        ),
    ]
