# Generated by Django 4.2.23 on 2025-08-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='ecommerce/products/images/default-product.jpg', help_text='Main product image', upload_to='ecommerce/products/images/'),
        ),
    ]
