# Generated by Django 4.2.23 on 2025-08-27 04:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the UOM', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unit name (e.g., kilogram, liter, piece)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the unit')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the UOM was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the UOM was last updated')),
            ],
            options={
                'verbose_name': 'Unit of Measure',
                'verbose_name_plural': 'Units of Measure',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the product price', primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the price was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the price was last updated')),
                ('product', models.ForeignKey(help_text='Product this price belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='ecommerce.product')),
                ('unit_of_measure', models.ForeignKey(help_text='Unit of measure for this price', on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='ecommerce.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Product Price',
                'verbose_name_plural': 'Product Prices',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'unit_of_measure')},
            },
        ),
    ]
