# Generated by Django 4.2.23 on 2025-10-12 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0007_unitofmeasure_productprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUnitOfMeasure',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for the UOM')),
                ('name', models.CharField(db_index=True, help_text='Unit name (e.g., kilogram, liter, piece)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description of the unit')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='When the UOM was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='When the UOM was last updated')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Unit of Measure',
                'verbose_name_plural': 'historical Units of Measure',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
