# Generated by Django 4.2.23 on 2025-10-13 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0008_historicalunitofmeasure'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProductCategory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for the category')),
                ('name', models.CharField(db_index=True, help_text='Category name (must be unique)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description of the category', null=True)),
                ('slug', models.SlugField(blank=True, help_text='SEO-friendly URL slug (auto-generated from name)', max_length=120)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active and visible')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this category should be featured prominently')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='When the category was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='When the category was last updated')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Categorys',
                'verbose_name_plural': 'historical Categories',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
