# Generated by Django 4.2.23 on 2025-10-13 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0009_historicalproductcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProductSubCategory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for the subcategory')),
                ('name', models.CharField(help_text='Subcategory name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description of the subcategory', null=True)),
                ('slug', models.SlugField(blank=True, help_text='SEO-friendly URL slug (auto-generated from name)', max_length=120)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subcategory is active and visible')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this subcategory should be featured prominently')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='When the subcategory was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='When the subcategory was last updated')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, help_text='Parent category for this subcategory', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ecommerce.productcategory')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Product SubCategory',
                'verbose_name_plural': 'historical Product SubCategories',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
