# Generated by Django 4.2.23 on 2025-10-13 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0010_historicalproductsubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for the product')),
                ('image', models.TextField(help_text='Main product image', max_length=100)),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('slug', models.SlugField(help_text='SEO-friendly URL slug (auto-generated from name)', max_length=220)),
                ('description', models.TextField(help_text='Detailed description of the product')),
                ('available_stock', models.PositiveIntegerField(default=0, help_text='Available stock quantity')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', help_text='Product status', max_length=10)),
                ('approval_status', models.CharField(choices=[('pending', 'Waiting for approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status of the product by admin', max_length=10)),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='When the product was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='When the product was last updated')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, help_text='Category for this product', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ecommerce.productcategory')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='User who owns this product', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Product',
                'verbose_name_plural': 'historical Products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
