# Generated by Django 4.2.23 on 2025-10-13 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0011_historicalproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProductPrice',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for the product price')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='When the price was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='When the price was last updated')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, help_text='Product this price belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ecommerce.product')),
                ('unit_of_measure', models.ForeignKey(blank=True, db_constraint=False, help_text='Unit of measure for this price', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ecommerce.unitofmeasure')),
            ],
            options={
                'verbose_name': 'historical Product Price',
                'verbose_name_plural': 'historical Product Prices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
