# Generated by Django 4.2.23 on 2025-10-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_historicalproductprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='condition',
            field=models.CharField(choices=[('SECOND', 'New'), ('SECOND', 'Second')], default='SECOND', help_text='Condition of the product (new or second-hand)', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('SECOND', 'New'), ('SECOND', 'Second')], default='SECOND', help_text='Condition of the product (new or second-hand)', max_length=10),
        ),
    ]
