# Generated by Django 4.2.23 on 2025-10-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_historicalproduct_condition_product_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('SECOND', 'Second')], default='NEW', help_text='Condition of the product (new or second-hand)', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('SECOND', 'Second')], default='NEW', help_text='Condition of the product (new or second-hand)', max_length=10),
        ),
    ]
