# Generated by Django 4.2.23 on 2025-10-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_alter_historicalproduct_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='weight_unit',
            field=models.CharField(choices=[('GRAM', 'Gram'), ('KG', 'Kilogram')], default='GRAM', help_text='Unit of weight (gram or kilogram)', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('GRAM', 'Gram'), ('KG', 'Kilogram')], default='GRAM', help_text='Unit of weight (gram or kilogram)', max_length=10),
        ),
    ]
