# Generated by Django 4.2.23 on 2025-10-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_historicalproduct_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Height of the product (in cm)', max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Length of the product (in cm)', max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Width of the product (in cm)', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Height of the product (in cm)', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Length of the product (in cm)', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Width of the product (in cm)', max_digits=10),
        ),
    ]
