# Generated by Django 4.2.23 on 2025-10-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_historicalproduct_height_historicalproduct_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='is_cod_allowed',
            field=models.BooleanField(default=False, help_text='Whether Cash on Delivery (COD) is allowed for this product'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_cod_allowed',
            field=models.BooleanField(default=False, help_text='Whether Cash on Delivery (COD) is allowed for this product'),
        ),
    ]
