# Generated by Django 4.2.17 on 2025-03-18 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('thinkflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdisease',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
