# Generated by Django 4.2.17 on 2025-03-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkflow', '0002_alter_plantdisease_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdisease',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdisease',
            name='disease_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='plantdisease',
            name='mini_article',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='plantdisease',
            name='preventive_measures',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdisease',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='plantdisease',
            name='symptoms',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdisease',
            name='treatment_recommendations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
