# Generated by Django 4.2.17 on 2025-03-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thinkflow', '0003_plantdisease_confidence_plantdisease_disease_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantdisease',
            name='details',
        ),
    ]
