# Generated by Django 4.2.17 on 2025-03-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkflow', '0004_remove_plantdisease_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdisease',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plantdisease',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plantdisease',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
