# Generated by Django 4.2.17 on 2025-03-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkflow', '0005_plantdisease_input_tokens_plantdisease_output_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdisease',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plantdisease',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plantdisease',
            name='total_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
