# Generated by Django 4.2.17 on 2025-01-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expired_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
