# Generated by Django 4.2.17 on 2025-02-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_follow_follow_cannot_follow_self_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='headline',
            field=models.CharField(default='', max_length=255),
        ),
    ]
