# Generated by Django 4.2.17 on 2025-02-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='farmer_community',
            field=models.CharField(default='', max_length=255),
        ),
    ]
