# Generated by Django 4.2.17 on 2025-02-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_city_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='farmer_community',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
