# Generated by Django 4.2.17 on 2025-02-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_picture_url',
            field=models.ImageField(blank=True, upload_to='cover-pictures'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture_url',
            field=models.ImageField(blank=True, upload_to='profile-pictures'),
        ),
        migrations.AddField(
            model_name='profile',
            name='thumbnail_picture_url',
            field=models.ImageField(blank=True, upload_to='thumbnail-pictures'),
        ),
    ]
