# Generated by Django 4.2.17 on 2025-02-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_cover_picture_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='thumbnail_picture_url',
            new_name='thumbnail_profile_picture_url',
        ),
    ]
