# Generated by Django 4.2.17 on 2025-02-11 09:54

from django.db import migrations
import django_tidb.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=django_tidb.fields.BigAutoRandomField(auto_created=True, primary_key=True, range=64, serialize=False, shard_bits=5, verbose_name='ID'),
        ),
    ]
