# Generated by Django 4.2.23 on 2025-07-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='potentially_harmful',
            field=models.BooleanField(default=False, help_text='Indicates if the post has been flagged as potentially harmful.'),
        ),
    ]
