# Generated by Django 4.2.23 on 2025-07-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0003_post_potentially_harmful'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='potentially_harmful',
            new_name='is_potentially_harmful',
        ),
    ]
