# Generated by Django 4.2.23 on 2025-07-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0007_postsaved_postsaved_unique_post_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('only_me', 'Only Me')], default='public', help_text='Privacy setting for the post', max_length=10),
        ),
    ]
