# Generated by Django 4.2.23 on 2025-08-01 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_media', '0009_alter_post_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SP', 'Spam'), ('HR', 'Hate Speech'), ('VL', 'Violence'), ('NU', 'Nudity'), ('MI', 'Misinformation'), ('BU', 'Bullying'), ('OT', 'Other')], db_index=True, help_text='Reason code for the report', max_length=2)),
                ('detail_reason', models.TextField(blank=True, help_text='Optional additional explanation from the reporter')),
                ('restrict_user', models.BooleanField(default=False, help_text='Whether reporter wants to hide content from this post author')),
                ('block_user', models.BooleanField(default=False, help_text='Whether reporter wants to block the post author entirely')),
                ('is_approved', models.BooleanField(db_index=True, default=False, help_text='Whether a moderator has approved this report')),
                ('approved_by', models.CharField(blank=True, help_text='Username/ID of moderator who approved the report', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the report was created')),
                ('created_by', models.CharField(help_text='Username/ID of the user who created the report', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the report status was updated')),
                ('updated_by', models.CharField(blank=True, help_text='Username/ID of who last updated the report', max_length=150)),
                ('post', models.ForeignKey(help_text='The post being reported', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='social_media.post')),
                ('user', models.ForeignKey(help_text='The user who made the report', on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_post_report'),
        ),
    ]
