# Generated by Django 4.2.23 on 2025-08-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0010_report_report_unique_post_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('SP', 'Spam'), ('HS', 'Hate Speech'), ('VL', 'Violence'), ('NU', 'Nudity'), ('MI', 'Misinformation'), ('BU', 'Bullying'), ('OT', 'Other')], db_index=True, help_text='Reason code for the report', max_length=2),
        ),
    ]
