# Generated by Django 4.2.23 on 2025-08-05 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address_detail', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('vendor_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('id_card_photo', models.ImageField(blank=True, upload_to='vendors/individual/')),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('business_number', models.CharField(blank=True, max_length=255)),
                ('business_nib', models.ImageField(blank=True, upload_to='vendors/company/nib/')),
                ('npwp', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='vendors/logos/')),
                ('address', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
