# Generated by Django 4.2.23 on 2025-08-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['vendor_type', 'review_status'], name='vendors_ven_vendor__1d45a0_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['user'], name='vendors_ven_user_id_d902b7_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['province', 'city', 'district'], name='vendors_ven_provinc_ddc362_idx'),
        ),
    ]
