# Generated by Django 4.2.23 on 2025-09-11 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_city_options_alter_country_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0002_vendor_vendors_ven_vendor__1d45a0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(help_text='Primary business address', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address_detail',
            field=models.CharField(help_text='Detailed address information', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='business_name',
            field=models.CharField(blank=True, help_text='Official registered business name', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='business_nib',
            field=models.ImageField(blank=True, help_text='NIB (Business Identification Number) document', upload_to='vendors/company/nib/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='business_number',
            field=models.CharField(blank=True, help_text='Official business registration number', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.ForeignKey(help_text='City where the vendor is located', on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='location.city'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the vendor record was created'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='district',
            field=models.ForeignKey(help_text='District/subdistrict where the vendor is located', on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='location.district'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full legal name of individual vendor', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id_card_photo',
            field=models.ImageField(blank=True, help_text='Photo of government ID card for verification', upload_to='vendors/individual/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='latitude',
            field=models.DecimalField(decimal_places=6, help_text='GPS latitude coordinate', max_digits=9),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, help_text='Vendor logo image', upload_to='vendors/logos/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='longitude',
            field=models.DecimalField(decimal_places=6, help_text='GPS longitude coordinate', max_digits=9),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(help_text='Display name for the store or business', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='npwp',
            field=models.CharField(blank=True, help_text='NPWP (Taxpayer Registration Number)', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(help_text='Contact phone number for the vendor', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='postal_code',
            field=models.CharField(help_text='Postal/ZIP code', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='province',
            field=models.ForeignKey(help_text='Province where the vendor is located', on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='location.province'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Admin notes and feedback for the review process'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='review_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Resubmission', 'Resubmission')], default='Pending', help_text='Current status in the vendor approval process', max_length=25),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the vendor record was last updated'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='user',
            field=models.ForeignKey(help_text='The user account associated with this vendor', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', help_text='Type of vendor: individual person or registered company', max_length=10),
        ),
    ]
