# Generated by Django 4.2.23 on 2025-09-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendor_address_alter_vendor_address_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESUBMISSION', 'Resubmission')], default='PENDING', help_text='Current status in the vendor approval process', max_length=25),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company')], default='INDIVIDUAL', help_text='Type of vendor: individual person or registered company', max_length=10),
        ),
    ]
