# Generated by Django 4.2.23 on 2025-09-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_vendor_review_status_alter_vendor_vendor_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='npwp',
            new_name='npwp_number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='business_nib',
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_nib_file',
            field=models.FileField(blank=True, help_text='NIB (Business Identification Number) document', upload_to='vendors/company/nib/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='npwp_file',
            field=models.FileField(blank=True, help_text='NPWP (Taxpayer Registration Number) file', max_length=255, upload_to=''),
        ),
    ]
