# Generated by Django 4.2.23 on 2025-10-09 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0002_alter_city_options_alter_country_options_and_more'),
        ('vendors', '0005_rename_npwp_vendor_npwp_number_remove_vendor_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVendor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('vendor_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company')], default='INDIVIDUAL', help_text='Type of vendor: individual person or registered company', max_length=10)),
                ('phone_number', models.CharField(help_text='Contact phone number for the vendor', max_length=20)),
                ('name', models.CharField(help_text='Display name for the store or business', max_length=255)),
                ('full_name', models.CharField(blank=True, help_text='Full legal name of individual vendor', max_length=255)),
                ('id_card_photo', models.TextField(blank=True, help_text='Photo of government ID card for verification', max_length=100)),
                ('logo', models.TextField(blank=True, help_text='Vendor logo image', max_length=100)),
                ('business_number', models.CharField(blank=True, help_text='Official business registration number', max_length=255)),
                ('business_nib_file', models.TextField(blank=True, help_text='NIB (Business Identification Number) document', max_length=100)),
                ('npwp_number', models.CharField(blank=True, help_text='NPWP (Taxpayer Registration Number)', max_length=255)),
                ('npwp_file', models.TextField(blank=True, help_text='NPWP (Taxpayer Registration Number) file', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='GPS latitude coordinate', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='GPS longitude coordinate', max_digits=9)),
                ('address_detail', models.CharField(help_text='Detailed address information', max_length=255)),
                ('postal_code', models.CharField(help_text='Postal/ZIP code', max_length=20)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESUBMISSION', 'Resubmission')], default='PENDING', help_text='Current status in the vendor approval process', max_length=25)),
                ('review_notes', models.TextField(blank=True, help_text='Admin notes and feedback for the review process')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='When the vendor record was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='When the vendor record was last updated')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('city', models.ForeignKey(blank=True, db_constraint=False, help_text='City where the vendor is located', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.city')),
                ('district', models.ForeignKey(blank=True, db_constraint=False, help_text='District/subdistrict where the vendor is located', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.district')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(blank=True, db_constraint=False, help_text='Province where the vendor is located', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.province')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='The user account associated with this vendor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical vendor',
                'verbose_name_plural': 'historical vendors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
