#!/usr/bin/env bash


### Upload database backups to AWS S3 (or S3-compatible storage like Cloudflare R2).
###
### Usage:
###     $ docker compose -f docker-compose.production.yml run --rm awscli upload


set -o errexit
set -o pipefail
set -o nounset


working_dir="$(dirname ${0})"
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"


message_welcome "Uploading backups to AWS S3..."


export AWS_ACCESS_KEY_ID="${AWS_S3_ACCESS_KEY_ID}"
export AWS_SECRET_ACCESS_KEY="${AWS_S3_SECRET_ACCESS_KEY}"

if [[ -n "${AWS_S3_ENDPOINT_URL:-}" ]]; then
    ENDPOINT_ARG="--endpoint-url ${AWS_S3_ENDPOINT_URL}"
else
    ENDPOINT_ARG=""
fi

aws s3 cp ${BACKUP_DIR_PATH} s3://${AWS_STORAGE_BUCKET_NAME}${BACKUP_DIR_PATH} --recursive ${ENDPOINT_ARG}


message_success "Backups uploaded successfully. Cleaning up local copies..."


rm -rf ${BACKUP_DIR_PATH}/*


message_success "Upload complete and local backups cleaned."
